version: '3'

services:
  spring:
    image: maven:3.6.0-jdk-8-alpine
    container_name: spring
    working_dir: /spring
    volumes:
      - ./:/spring
    ports:
      - 8080:8080
    command: mvn spring-boot:run

  redis:
    image: redis:5.0.4-alpine
    container_name: redis
    ports:
      - 6379:6379